version: '3.3'

services:
  db:
    restart: always
    image: postgres:9.5
    environment:
      - POSTGRES_DB=holiday
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"


  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/not-holiday/
    ports:
      - "8000:8000"
    depends_on:
      - db

