version: '3.3'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=holiday


    ports:
      - "3306:3306"


  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/not-holiday/
    ports:
      - "8000:8000"
    depends_on:
      - db

